### ISSUE TITLE
Support for Sidekiq 7?

### ISSUE THREAD

**Issue by thenathanjones** [zormandi/logcraft-sidekiq#1]
Hello! 

First off, nice library. I fired it up and noted that all the versions for my Sidekiq-related gems were downgraded to earlier versions. I was wondering if there were any issues preventing it from being used with Sidekiq 7, or whether it may be just that a new version hasn't been published since it was released?

Thanks in advance!

Cheers,
Nathan

**Comment by zormandi** [comment]
Hi,

To be honest, I haven't looked into compatibility with Sidekiq 7 yet (I've been working on other projects) so it may be that simply releasing the version restriction would be enough, but I can't say for sure. We'd need to add Sidekiq 7 to the test matrix to make sure. Feel free to submit a PR or if you can wait then I can probably get around to doing it in the next 1-2 weeks.

Cheers,
Z

**Comment by thenathanjones** [comment]
Hey Z!

Thanks for the quick reply, that makes total sense. I'll have a poke around and see what's involved in getting a meaningful PR up.

Cheers,
Nathan

**Comment by zormandi** [comment]
Best case scenario: you just need to create a new gemfile and add the Sidekiq version to the GitHub Actions workflow. Unless the tests break... 😀

**Comment by thenathanjones** [comment]
Well, let's see what that does then 😅

**Comment by zormandi** [comment]
The new version is released. I hope everything will work for you as expected.

**Comment by thenathanjones** [comment]
Will give this a try. Thank you very much! 🙇
